name: mdp2
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #core
  equatable: ^2.0.5
  flutter_dotenv: ^5.2.1
  flutter_i18n: ^0.36.2
  json_annotation: ^4.9.0

  #network
  dio: ^5.7.0

  #state management
  flutter_riverpod: ^2.6.1
  riverpod_generator: ^2.6.2
  riverpod_annotation: ^2.6.1

  #navigation
  auto_route: ^9.2.2

  #util
  connectivity_plus: ^6.1.0
  logger: ^2.4.0
  cached_network_image: ^3.4.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  json_serializable: ^6.8.0
  


flutter:

  
  uses-material-design: true

  assets:
    - .env
    - assets/i18n/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
